### ISSUE TITLE
Psych.dump parity: missing ---, quoting, sequence indent; yeptris/yaml standalone load; drop-in path moved

### ISSUE THREAD

**Issue by ronaldtse** [leptris/yeptris-ruby#95]
## `Yeptris::Psych.dump` is not Psych-parity (3 divergences), and two 0.5.0.1 defects

Reproducer (yeptris 0.5.0.1, arm64-darwin):

```ruby
require "psych"
require "yeptris"
require "yeptris/yaml"
require "yeptris/psych"

h = { "content" => "PD (1994-01-01)", "tech_note_number" => "5014", "sym" => :a,
       "nest" => { "x" => [1, 2] } }
puts ::Psych.dump(h).inspect
puts Yeptris::Psych.dump(h).inspect
```

```
stdlib Psych.dump:  "---\ncontent: PD (1994-01-01)\ntech_note_number: '5014'\nsym: :a\nnest:\n  x:\n  - 1\n  - 2\n"
Yeptris::Psych.dump: "content: PD (1994-01-01)\ntech_note_number: \"5014\"\nsym: :a\nnest:\n  x:\n    - 1\n    - 2\n"
```

### Divergences

| aspect | stdlib Psych | Yeptris 0.5.0.1 |
|---|---|---|
| document start | `---\n` | **absent** |
| digit-leading string | `'5014'` (single-quoted — type-preserving on load) | `"5014"` (double-quoted) |
| sequence indentation under a mapping key | 2 spaces (`  - 1`) | 4 spaces (`    - 1`) |

Consumers that byte-compare serialized YAML (relaton's `Version#to_yaml` round-trip specs, relaton's adobe ext `tech_note_number: '5014'`, relaton-cli's db `serialize` output) all fail against 0.5.0.1 on these.

### Bug 2: `require "yeptris/yaml"` is not self-sufficient

`lib/yeptris/yaml.rb` references `Yeptris::FFI` (and, past that, `Document` inside `BulkBuilder`) without requiring `yeptris/ffi`/`yeptris`. Requiring the neutral surface directly — which lutaml-model's `yaml/adapter/yeptris_adapter.rb` does — raises `NameError: uninitialized constant Yeptris::FFI` unless the full `require "yeptris"` already happened.

### Bug 3 (breaking change): the drop-in rebind moved with no compat path

0.4's documented drop-in `require "yeptris/psych"` no longer rebinds the top-level `Psych` — it now only defines the namespace, and the rebind lives at `require "yeptris/psych/drop_in"`. Consumers following the 0.4 contract (relaton) silently stay on stdlib Psych after upgrading. Worth a release note at minimum; a deprecation warn on the old path would have caught it.

Context: relaton's moxml/leptris/yeptris migration (relaton#168) pinned lutaml-model's yeptris yaml adapter to generate through `Yeptris::Psych.dump` for exactly this parity contract — these three divergences are the last red on that matrix.

**Comment by ronaldtse** [comment]
### Bug 4: missing `Psych.load_tags` class API

The drop-in namespace lacks stdlib Psych's class-level tag registry. Under the rebind, any code calling `Psych.load_tags` (stdlib's own Visitors use it; lutaml-model's standard YAML adapter path reaches it) raises `NoMethodError: undefined method 'load_tags' for module Yeptris::Psych` — 18 spec failures in relaton's suite (db/registry `processors_by_prefix` path) as soon as the rebind is active.

**Comment by ronaldtse** [comment]
All five findings are fixed and released — verified against the **published** gem (yeptris-ruby 0.5.2.1, lockstep with libyeptris v0.5.2):

```
stdlib:  "---\ncontent: PD (1994-01-01)\ntech_note_number: '5014'\nsym: :a\nnest:\n  x:\n  - 1\n  - 2\nempty: []\n"
yeptris: "---\ncontent: PD (1994-01-01)\ntech_note_number: '5014'\nsym: :a\nnest:\n  x:\n  - 1\n  - 2\nempty: []\n"
```

- **`---` marker** — `explicit_doc_start` (C v0.5.0) wired through `Yeptris::Psych.dump` (PR #93).
- **`'5014'` quoting** — both dump builders now share one quoting table porting psych `visit_String`'s matrix verbatim (y/Y/n/N and leading-indicator → double; type-ambiguous → single; else plain), C side PR yeptris#284.
- **sequence indent** — a block seq under a mapping key sits at the key's column, libyaml's form (yeptris#284); empty collections ride the key line (`empty: []`, yeptris#287 — the first cut of the indent change made an empty seq emit an invalid next-line `[]`, caught by yeptris-py's differential).
- **`require "yeptris/yaml"` standalone** — the file now requires `yeptris` itself (PR #93).
- **drop-in path** — the rebind move was deliberate (#69: coexistence in any load order); the old path now prints a migration warning pointing at `yeptris/psych/drop_in` instead of silently doing nothing (PR #93). Note the issue text's premise was slightly off: the opt-in change shipped in v0.2.0.1, not 0.5.

Known remaining cosmetic gaps (round-trip-correct, not byte-identical to psych, tracked for a follow-up): multiline strings double-quote instead of literal blocks, `"<<"` lacks psych's `!!str` tag.

Releases: libyeptris v0.5.1/v0.5.2, yeptris-ruby 0.5.1.1 → 0.5.2.1 (PRs #93, #96, #97).

**Comment by ronaldtse** [comment]
## Validation of `fix/psych-doc-header` (fe8213e + working tree, 2026-09-16)

Direct byte-comparison vs stdlib Psych (`/tmp/parity95.rb`-style probe, vendored libyeptris.dylib):

| bug | status |
|---|---|
| 1a `---` separator | **fixed** |
| 1b quoting (digit-leading strings `'5014'`, symbols, `"y"`) | **fixed** (but see new regression issue, over-matching) |
| 1c sequence indent under nested mappings | **still open** |
| 2 `yeptris/yaml` self-sufficiency | **fixed** |
| 3 drop-in path move | warn added — good migration signal |
| 4 `Psych.load_tags` | **still open** |

### 1c — reproducer

```ruby
require "psych"; require "yeptris"; require "yeptris/psych"
::Psych.dump({ "nest" => { "x" => [1, 2] } })
# "---\nnest:\n  x:\n  - 1\n  - 2\n"        (sequences at ANY depth: 2-space step, no extra indent for the sequence itself)
Yeptris::Psych.dump({ "nest" => { "x" => [1, 2] } })
# "---\nnest:\n  x:\n    - 1\n    - 2\n"    (extra indent level on the nested sequence)
```

Top-level-key sequences (`title:\n  - content: ...`) already match; only sequences nested deeper than the first level gain the extra indent. This is also the remaining divergence in the relaton-cli `serialize → YAML` shape (`SubcommandDb fetch all entries return YAML`).

### 4 — reproducer

```ruby
require "yeptris/psych"
Yeptris::Psych.respond_to?(:load_tags)  # => false
```

Stdlib Psych exposes the class-level tag registry (`load_tags`/`dump_tags`/`domain_types`, psych.rb:718) and its own visitors read it. Under the drop-in rebind this is the single largest CI failure driver in the relaton matrix (52 × `NoMethodError: undefined method 'load_tags' for module Yeptris::Psych`, ~29 suites).

Both close with this issue's fix set — everything else on the consumer side (relaton#168, lutaml-model#779 wiring) is already in place and inherits them unchanged.

**Comment by ronaldtse** [comment]
New defect introduced by the fix branch (the 1b caveat in the table above): #99 — `dump` over-quotes String-resolving multi-dot numerics; the branch's own `psych_doc_marker_spec` fails on `"1.2.3"`.

**Comment by ronaldtse** [comment]
**Reopened item (bug 4): `Psych.load_tags` is still missing in the 0.6.0.1 releases.**

Validated on 0.6.0.1 just now: dump parity is **fully fixed** (`---`, quoting incl. `"1.2.3"` plain, nested-sequence indent — byte-identical with stdlib Psych on the #95 reproducer hash; also #99 confirmed fixed), but:

```ruby
require "psych"
require "yeptris/psych/drop_in"
Psych.respond_to?(:load_tags)  # => false
```

Stdlib defines the class-level registry (`load_tags`/`dump_tags`/`domain_types`, psych.rb:718) and Psych's own visitors read it. Under the drop-in this still drives 26× `NoMethodError: undefined method 'load_tags'` in relaton's suite (db/registry `processors_by_prefix` path) — it is the last remaining blocker from the consumer side. Everything else in the relaton matrix is now unblocked by the 0.6 parity work.

**Comment by ronaldtse** [comment]
**Bug 4 (`Psych.load_tags`) is fixed in 0.6.1.2** — `Yeptris::Psych.load_tags` / `dump_tags` now exist as the class-level registries and are honored on both sides:

```ruby
Psych.respond_to?(:load_tags)          # => true (the drop-in rebind)
Psych.load_tags["!mygem/shape"] = Klass
Psych.unsafe_load("--- !mygem/shape\nx: 1\ny: two\n")  # => Klass revived via init_with
Psych.dump_tags[Klass] = "!mygem/shape"  # => the dumped root tag rides it
```

Revival goes through the coder protocol (`init_with`) over the mapping's own top-level pairs — the `!ruby/object` safety boundary (Encodable opt-in) is unchanged. Pinned in `spec/psych_issue300_spec.rb` (PR #108, released 0.6.1.2 across all platforms incl. the new Windows x64-mingw-ucrt gem).

One emitter follow-up noted there: custom ROOT tags currently render in the verbatim own-line form (`!<!mygem/point>`), not Psych's inline `--- !mygem/point` — the inline form closes the dump_tags round-trip and is tracked with #300's family 2.

**Comment by ronaldtse** [comment]
## 0.6.1.2 follow-up: `Psych.load_tags` fixed, but `dump_tags` / `domain_types` class-level accessors still missing

`load_tags` verified present in 0.6.1.2 — thank you.

The stdlib `Psych` singleton also carries two more registry accessors (psych.rb:718), which consumers call the same way:

```ruby
require "psych"
require "yeptris/psych/drop_in"

Psych.dump_tags       # NoMethodError: undefined method 'domain_types' for module Yeptris::Psych (via lutaml-model's standard yaml adapter read path)
Psych.domain_types    # NoMethodError: undefined method 'domain_types' for module Yeptris::Psych
```

Under the rebind, lutaml-model's standard YAML adapter path and pubid-flavor resolution in relaton both reach these: 31 spec failures in relaton's suite (26× `domain_types`, 5× `write` downstream of an unfilled registry — `Regexp#last_match`-style consumers of `dump_tags` are the source).

Suggested: mirror the stdlib trio — `load_tags` (done), `dump_tags`, `domain_types` — as class-level attr accessors on `Yeptris::Psych`, honored by the dump/load faces the same way the rebind now honors `load_tags`.

**Comment by ronaldtse** [comment]
Fixed in **0.6.1.3** (rubygems, all platforms incl. the Windows x64-mingw-ucrt gem):

- `Psych.domain_types` exists as the third class-level registry (the 26× `undefined method` under the rebind is gone), with stdlib's full helper set: `add_domain_type(domain, type_tag, &block)`, `add_builtin_type`, `remove_type`, and `add_tag` (which writes both `load_tags` and `dump_tags`).
- The revival visitor applies registered domain blocks per tagged node — stdlib ToRuby#accept's post-pass semantics, same tag normalization (strip leading `!`/`/`, ensure the `tag:` prefix unless `x-private`).
- `dump_tags` writes work (the "unfilled registry" writes land and ride the dump: a class registered via `add_tag`/`dump_tags` emits its custom root tag).

Pinned in `spec/psych_domain_types_spec.rb` (PR #110). If relaton's suite still shows any of the 31 failures after 0.6.1.3, the residue would be the inline-root-tag emitter form (`--- !mygem/point` vs the verbatim own-line rendering) — that one rides the emitter pass with #300's family 2.

**Comment by ronaldtse** [comment]
## 0.6.1.3 validation: registry APIs ✓, two drop-in gaps remain

`load_tags` / `dump_tags` / `domain_types` all present and honored — the registry half of this issue is fully fixed, thank you.

Two Psych-compat completeness gaps remain under the drop-in, each with an isolated reproducer:

### A. `Hash#to_yaml` raises inside the drop-in's core_ext

```ruby
require "psych"
require "yeptris/psych/drop_in"
{ docidentifier: [{ content: "ISO 123" }] }.to_yaml
# NoMethodError: undefined method 'write' for an instance of Hash
```

The drop-in's `Object#to_yaml` reaches a `yaml`/emit call passing the receiver where an IO-like is expected. Stdlib psych's `Object#to_yaml` is `Psych.dump(self, options)` — string-returning, no IO. relaton's `Db#search_edition_year` (`{ docidentifier: [...] }.to_yaml`) and every hash-serialization caller break on this.

### B. `Psych::Visitors::YAMLTree.create` class method missing

```ruby
require "yeptris/psych/drop_in"
Yeptris::Psych::Visitors::YAMLTree.respond_to?(:create)  # => false
```

Stdlib psych exposes `YAMLTree.create` (the factory the emitter paths call); yeptris's drop-in visitors only define the instance. Callers using the factory pattern (relaton's db cache serialization via lutaml/psych-compatible emitters) fail with `undefined method 'create' for class Yeptris::Psych::Visitors::YAMLTree`.

Both close with stdlib-parity on the drop-in surface; consumer wiring (relaton#168, lutaml-model#779) is already final and inherits them unchanged.

**Comment by ronaldtse** [comment]
## Last two drop-in gaps on 0.6.2.2: stdlib `Psych.dump`'s two-arg call contract

With relaton now on lutaml-model 0.8.33 (yeptris adapter) + the drop-in rebind, only 4 spec failures remain across relaton's whole matrix — all one call path:

stdlib psych.rb:

```ruby
def self.dump o, io = nil, options = {}
  if Hash === io
    options = io
    io      = nil
  end
  visitor = Psych::Visitors::YAMLTree.create options
  visitor << o            # ← THE << EMITTER FACE
  visitor.tree.yaml io, options
end
```

1. **`Yeptris::Psych.dump(obj, options_hash)`** must treat a Hash second argument as options (stdlib's `if Hash === io` swap) — currently the options hash falls into the io path (earlier versions crashed `write`; 0.6.2.x silently misroutes).
2. **`Yeptris::Psych::Visitors::YAMLTree#<<`** must exist as the emitter entry (stdlib's dump pushes objects through `<<`; `create` exists on 0.6.2.x but `<<` does not — anything that reaches a stdlib-shaped `Psych.dump` under the rebind, e.g. VCR's cassette serialization inside `@db.fetch` specs, dies with `undefined method '<<'`).

Reproducer of the exact failing frame:

```ruby
require "psych"
require "yeptris/psych/drop_in"
# anything calling the stdlib two-arg shape under the rebind:
Psych.dump({ a: 1 }, {})   # or an emitter that does YAMLTree.create(...).<<(obj)
```

With `<<` added to YAMLTree and the Hash-io swap honored, relaton#168's remaining 4 failures close. Everything else — dump byte parity, load_tags/dump_tags/domain_types, standalone requires — is verified fixed on 0.6.2.2.

**Comment by ronaldtse** [comment]
/tmp/issue95-close.md

**Comment by ronaldtse** [comment]
Both frames are closed in **0.6.3.2** (rubygems, all 6 platforms, clean-install verified):

**1. `Psych.dump(obj, options_hash)` — the Hash-io swap.** Verified working on shipped 0.6.2.2 already (isolated repro: `Psych.dump({ a: 1 }, {})` → `"---\na: 1\n"`); now pinned by spec regardless.

**2. `YAMLTree#<<` and the dump tail.** `Psych::Visitors::YAMLTree` now carries stdlib's full emitter contract:
- `alias_method :<<, :push` — the `<<` push face (psych 5.5's own spelling)
- `#tree` → `BuiltDocument#yaml(io = nil, options = {})` — stdlib dump's serialization tail (`visitor.tree.yaml io, options`): returns the `---\n`-prefixed string, or writes and returns the io. So the complete stdlib body — `YAMLTree.create(options)` → `visitor << o` → `visitor.tree.yaml io, options` — runs unchanged under the rebind:

```ruby
v = Psych::Visitors::YAMLTree.create({})
v << { "a" => [1, "two"] }
v.tree.yaml   # => "---\na:\n- 1\n- two\n"
```

PR #118 (specs in `spec/psych_issue95_core_ext_spec.rb`). With relaton#168's remaining 4 failures tied to exactly these two frames, the whole matrix should clear on 0.6.3.2.

**Comment by ronaldtse** [comment]
## 0.6.4.1: the stdlib file/stream-level `Psych` API family is still missing under the drop-in

`YAMLTree#<<` and the Hash-io swap are fixed — thank you. Probing the rest of the stdlib singleton surface (psych.rb):

```ruby
                      stdlib   Yeptris 0.6.4.1
safe_load_file         yes     MISSING
load_file              yes     MISSING
unsafe_load_file       yes     MISSING
parse_file             yes     MISSING
safe_dump              yes     MISSING
load_stream            yes     MISSING
parse_stream           yes     yes ✓
```

First consumer hit: pubid main's `Pubid::Schema::Loader.load_joint_prefixes` calls `Psych.safe_load_file` — under the rebind it raises `NoMethodError: undefined method 'safe_load_file' for module Yeptris::Psych` (reproduced via `require "relaton"; require "pubid/iso"`).

Anything that reads YAML from disk through the rebind (`YAML.load_file` is aliased to `Psych.load_file` in stdlib yaml.rb) hits this family, so closing it should finish the drop-in's singleton parity.

**Comment by ronaldtse** [comment]
One more Psych-parity gap found while validating relaton#168 against 0.6.4.1: **`Psych.safe_load` on an ASCII-8BIT input returns ASCII-8BIT scalars; stdlib psych returns UTF-8** (a YAML stream is a Unicode character stream, and stdlib psych tags non-ASCII scalars UTF-8 even when the input string is binary).

Repro (with the drop-in rebind active):

```ruby
require "yaml"          # first — e.g. a spec_helper that loads yaml before relaton
puts YAML.safe_load("a: é".dup.force_encoding("ASCII-8BIT"))["a"].encoding
# => UTF-8              (stdlib psych 5.2.2)

require "relaton"       # requires "psych" then "yeptris/psych/drop_in"
puts YAML.safe_load("a: é".dup.force_encoding("ASCII-8BIT"))["a"].encoding
# => ASCII-8BIT         (yeptris)
```

Notes:
- The stdlib behavior is the contract here: Net::HTTP hands back bodies as ASCII-8BIT, and callers pass them straight to `safe_load`; downstream string comparisons then fail on encoding (`"..." == "..."` is false across encodings for non-ASCII).
- Interesting asymmetry: yeptris's `Yeptris::YAML`/`yeptris/yaml` face normalizes to UTF-8, but the rebound `Psych.safe_load` face preserves the input encoding. The parity target is the Psych face.
- In relaton this fails `spec/sdo` ("caches and reads a UTF-8 index delivered as a binary body") — that suite is otherwise green on moxml/leptris/yeptris.
